### ISSUE TITLE
Could this algo be applied to the tensor permute used in deep learning framework like pytorch?

### ISSUE THREAD

**Issue by leiwen83** [djns99/CUDA-Shuffle#10]
Hi,

Tensor manupulation at the top performance is always hard. I wander that whether your algo could be applied to the permutation op in the pytorch and achieve the peak performance?

**Comment by djns99** [comment]
I am not super familiar with pytorch, but I took a look and I am assuming you are talking about this implementation here: https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/caffe2/operators/batch_permutation_op.cu

Looking at that implementation it appears to take a list of indices and permutes based on that list. This is very similar to the last step in our algorithm so it is definitely possible. Specifically, our algorithm focuses on generating random permutations quickly and in parallel, so in this case it would be best suited to generating the initial random array of indices, rather than inside the BatchOp as it stands currently.

Alternatively, If you were wanting to change the API to not require the array of indices to be passed in, then our algorithm would also be suitable in that application, as each thread in `BatchPermutationKernel` would implement our algorithm to produce the random index rather than reading from the input buffer.

I am open to see this implemented in pytorch, so if you think this is something useful feel free to use it.
